---
abstract: 'fork-safe and easy transaction handling DBI handler'
author:
  - 'Atsushi Kobayashi <nekokak _at_ gmail _dot_ com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0.94
  Test::Requires: 0
  Test::SharedFork: 0.16
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Handler
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  DBI: 1.605
  DBIx::TransactionManager: 1.09
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/nekokak/p5-DBIx-Handler.git
version: 0.07
